### ISSUE TITLE
Graph no longer updating, straight line across now

### ISSUE THREAD

**Issue by thinksnow** [glitch452/MMM-CoinMarketCap#10]
The previous days on the 7-day chart show ups and downs, but as of Thursday, it's a straight line across and continuing. I did a hard reset, pull and install to make sure everything is current, but no change. I'm using the custom views almost exactly as they are listed in the example, and am pulling updates every 10 minutes, with a 30-second retry.

**Comment by onisuk** [comment]
Same problem here, guessing CoinBase changed the API again??

**Comment by glitch452** [comment]
Looks like CoinMarketCap switched to a new endpoint for the graphs.  I'm updating the module now.
