### ISSUE TITLE
Price does not show

### ISSUE THREAD

**Issue by memolfb** [glitch452/MMM-CoinMarketCap#11]
The price does not show for any type of view, I have the latest version, it only diplay the $ symbol.

**Comment by glitch452** [comment]
Can you post the config values for the module?

**Comment by memolfb** [comment]
Sure, here it is:

	{
		  module: 'MMM-CoinMarketCap',
		  position: 'bottom_right',
		  header: 'Crypto',
		  config: {
			apiKey: 'my api key',
			currencies: [
			  'bitcoin',
			  'ethereum',
			  'golem'
			],
			view: 'graphColored',
			fullWidthMode: true,
			logoColored: true,
			graphSize: 'small',
			fontSize: 'small',
			graphRange: 7,
			showCurrencyWithPrice: true,
			showColumnHeaders: false,
			updateInterval: 10,
			columns: [
			  'logo',
			  'name',
			  'price',
			  'graph'
			]
		  }
		},

**Comment by memolfb** [comment]
I just found out that if I change the language to 'us' in the main config it works, but I use the configuration in spanish 'es'.

**Comment by memolfb** [comment]
I will create the es.json file and send it to you if you want it, so others can use it if needed it.

**Comment by memolfb** [comment]
Well, the es.json file does not resolves this issue, I've modified the MMM-CoinMarketCap.js file and replaced the config.language parameter references to 'en' and now it works.

**Comment by glitch452** [comment]
Hi, I think I fund and fixed the bug.  Please pull the latest and give it a try and let me know!

Also, if you want to send over the es.jason file, I would love to include that in the module for anyone else who may benefit from that.  Thanks!

**Comment by memolfb** [comment]
Awesome!, thanks!

{
	"CURRENCY_TITLE": "Moneda",
	"PRICE_TITLE": "Precio ({conversion_var})",
	"PRICE_USD_TITLE": "Precio (USD)",
	"HOUR_TITLE": "Hora",
	"DAY_TITLE": "Día",
	"WEEK_TITLE": "Semana",
	"TREND_TITLE": "Tendencia ({range_var})",
	"CHANGES_TITLE": "Cambios",
	"ONE_DAY": "1 día",
	"ONE_WEEK": "1 semana",
	"ONE_MONTH": "1 mes",
	"UPDATE_SCHEDULED": "Actualización programada para ejecutarse automáticamente cada {minutes} minutos.",
	"LISTINGS_REQUESTED": "Solicitud enviada para listados de monedas.",
	"CURRENCY_UPDATE_REQUESTED": "Solicitud enviada para actualizar \"{name}\" utilizando el ID: {id}.",
	"UPDATE_STARTED": "Actualización iniciada.",
	"REQUEST_LOGO_DOWNLOAD": "Solicitando descarga de logo: \"{filename}\".",
	"LISTINGS_SUCCESS": "Listados obtenidos con éxito después de {numberOfAttempts} intento(s).",
	"LISTINGS_FAILURE": "Error al solicitar el listado, Intentando en {retryTimeInSeconds} segundos.",
	"CURRENCY_UPDATE_SUCCESS": "Actualización de moneda recibida para IDs: {id} después de {numberOfAttempts} intento(s).",
	"CURRENCY_UPDATE_FAILURE": "Error al actualizar la moneda para IDs: {id}. Intentando en {retryTimeInSeconds} segundos.",
	"LOGO_DOWNLOAD_SUCCESS": "Logo descargado con exito: \"{filename}\".",
	"LOGO_DOWNLOAD_FAILURE": "Error al descargar el logotipo de: \"{filename}\".",
	"INVALID_CURRENCY": "No se encontró moneda con ID: \"{id}\" o el nombre: \"{name}\".",
	"LOADING": "Cargando &hellip;",
	"API_ERROR": "No se pueden obtener datos de {website}.",
	"SUSPENDED": "Suspendido",
	"RESUMED": "Reanudado",
	"LOGO_SAVE_FAILURE": "Error al guardar \"{sourceFilename}\" como: \"{destinationFilename}\".",
	"LOGO_SAVE_SUCCESS": "Guardado exitosamente \"{sourceFilename}\" como: \"{destinationFilename}\".",
	"API_KEY_REQUIRED": "Ingresa tu llave API."
}
