### ISSUE TITLE
issue with xmlhttpreq something is depreciated and needs to be updated?

### ISSUE THREAD

**Issue by ghost** [glitch452/MMM-CoinMarketCap#12]
MMM-CoinMarketCap.js:794 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

**Comment by glitch452** [comment]
This is just a deprecation warning, not an actual error.  The synchronous xmlhttpreq call is being used to check if the images for the requested coins exist on the local system, not reaching out to the internet, so there is no performance issues caused by it.
