### ISSUE TITLE
Ability to hide local currency conversion 

### ISSUE THREAD

**Issue by ScrubDaddy69** [glitch452/MMM-CoinMarketCap#15]
Hello!

I was wondering if anyone knew what I could modify or do in order to hide the currency to the right of the price

It's not a big deal, I just don't find seeing 'USD'  to be aestheticly pleasing.

If anyone has feedback I really appreciate it, thank you for the module and your time!

**Comment by glitch452** [comment]
Hi, you should be able to set the `showCurrencyWithPrice` option to `false` in the config.

**Comment by ScrubDaddy69** [comment]
Wow, I can't believe I missed that. Thank you for helping!
