### ISSUE TITLE
Error messages on MM 2.17.1 (RESOLVED)

### ISSUE THREAD

**Issue by SdeGeata** [glitch452/MMM-CoinMarketCap#18]
Hello;

   I am currently installing my Magic Mirror modules on a new Raspberry pi4 with all the current versions. I have discovered a problem with this module. It throws errors on load and produces a black screen. Here is the log output:

`0|mm  | [01.10.2021 17:28.56.214] [ERROR] 
0|mm  | App threw an error during load
0|mm  | [01.10.2021 17:28.56.217] [ERROR] 
0|mm  | Error: Cannot find module 'request'
0|mm  | Require stack:
0|mm  | - /home/pi/MagicMirror/modules/MMM-CoinMarketCap/node_helper.js
0|mm  | - /home/pi/MagicMirror/js/app.js
0|mm  | - /home/pi/MagicMirror/js/electron.js
0|mm  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|mm  | - 
0|mm  |     at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
0|mm  |     at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
0|mm  |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|mm  |     at Module._load (internal/modules/cjs/loader.js:732:27)
0|mm  |     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
0|mm  |     at Module.require (internal/modules/cjs/loader.js:959:19)
0|mm  |     at require (internal/modules/cjs/helpers.js:88:18)
0|mm  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-CoinMarketCap/node_helper.js:14:15)
0|mm  |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
0|mm  | [01.10.2021 17:28.56.218] [ERROR] 
0|mm  | Whoops! There was an uncaught exception...
0|mm  | [01.10.2021 17:28.56.225] [ERROR] 
0|mm  | Error: Cannot find module 'request'
0|mm  | Require stack:
0|mm  | - /home/pi/MagicMirror/modules/MMM-CoinMarketCap/node_helper.js
0|mm  | - /home/pi/MagicMirror/js/app.js
0|mm  | - /home/pi/MagicMirror/js/electron.js
0|mm  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|mm  | - 
0|mm  |     at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
0|mm  |     at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
0|mm  |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|mm  |     at Module._load (internal/modules/cjs/loader.js:732:27)
0|mm  |     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
0|mm  |     at Module.require (internal/modules/cjs/loader.js:959:19)
0|mm  |     at require (internal/modules/cjs/helpers.js:88:18)
0|mm  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-CoinMarketCap/node_helper.js:14:15)
0|mm  |     at Module._compile (internal/modules/cjs/loader.js:1078:30)
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
0|mm  |   code: 'MODULE_NOT_FOUND',
0|mm  |   requireStack: [
0|mm  |     '/home/pi/MagicMirror/modules/MMM-CoinMarketCap/node_helper.js',
0|mm  |     '/home/pi/MagicMirror/js/app.js',
0|mm  |     '/home/pi/MagicMirror/js/electron.js',
0|mm  |     '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
0|mm  |     undefined
0|mm  |   ]
0|mm  | }
0|mm  | [01.10.2021 17:28.56.227] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm  | [01.10.2021 17:28.56.227] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues`

**Comment by glitch452** [comment]
Looks like the error is `Error: Cannot find module 'request'`.  Did you run the `npm install` for this module?

**Comment by glitch452** [comment]
I'm also running on a Raspi4 with the latest OS and latest MagicMirror, but I can't reproduce the problem.  It looks like it's missing the request module.  Maybe the `npm install` didn't work properly for MagicMirror?

**Comment by glitch452** [comment]
Alright, did some more digging, looks like I wasn't getting the latest mm version.  It appears that the request module is no longer included.  I may have to add a `package.json` to this repo to install it.

**Comment by glitch452** [comment]
Alright, I pushed up a new version with a a package file.  If you pull that and run `npm install`, that should do the trick.

**Comment by SdeGeata** [comment]
Hello @glitch452 !

That indeed fixed it! Thanks! Keep up the good work!
