### ISSUE TITLE
Conversion doesnt work

### ISSUE THREAD

**Issue by Zdenekslezak** [glitch452/MMM-CoinMarketCap#2]
Hi there,

I´m having problem with converting to USD (and to any other currency). If i try to add conversion: 'USD', it will not show any numbers, but just only š. If i try CZK i will show č etc. only EUR works. 

Is there any problem or am i doing somethink wrong? My config below:

                {
                        module: "MMM-CoinMarketCap",
                                position: "top_right",
                                config: {
                                        currencies: ['ethereum', 'bitcoin'],
                                        view: 'logo',
                                        conversion: "EUR",
                                         }
                },
                
Thank you!

**Comment by glitch452** [comment]
Unfortunately I am unable to reproduce the issue with the information provided.  This module uses the local number formatting functionality that is built into the browser used by MagicMirror core.  The issue is likely related to a system configuration.
