### ISSUE TITLE
Unable to get MMM-CoinMarketCap to work

### ISSUE THREAD

**Issue by TrevorHayes33** [glitch452/MMM-CoinMarketCap#23]
Hello,

I noticed that this module requires MagicMirror to be at LEAST update 2.2. However I am not finding any updates further than MagicMirror 2.18 online. Is there something I am doing wrong? Love how this module looks!

**Comment by glitch452** [comment]
Hi, yes, MM v2.18.0 is the latest, it was released a couple days ago.  I'm not sure what the issue is though, 2.18.0 is newer than 2.2.1 (18 > 2), so that's not a problem.

**Comment by onisuk** [comment]
Mine module stopped woking a while back, I made a new api key etc and still nothing... just blank module

**Comment by glitch452** [comment]
> Mine module stopped working a while back, I made a new api key etc and still nothing... just blank module

Hi, in general, the module does work.  I'm using it on my mirror.  So it would seem to be a problem on your end. I would suggest making sure the module and MagicMirror are up-to-date.

**Comment by Gradivis** [comment]
Just wanted to say that I am also having issues with the module displaying. I did a fresh install of MMM, followed the instructions to install your module, and copy-pasted the config exactly (with my API key from CMC). Not showing anything. Is there a way to troubleshoot this that you would recommend on my end?

**Comment by glitch452** [comment]
> Just wanted to say that I am also having issues with the module displaying. I did a fresh install of MMM, followed the instructions to install your module, and copy-pasted the config exactly (with my API key from CMC). Not showing anything. Is there a way to troubleshoot this that you would recommend on my end?
> 
> Edit: found the issue - I hadn't CDed into the modules directory when installing yours. Moving the files over the correct directory fixed it! Sorry for bothering you!

Glad you were able to get it going!

For the others, in general, to troubleshoot, check the console logs for both the NodeJs back-end, and the browser front-end.  Also make sure your underlying software is up to date (including the OS, Node, NPM, MagicMirror, etc...)
