### ISSUE TITLE
Graph not updating

### ISSUE THREAD

**Issue by adamlove86** [glitch452/MMM-CoinMarketCap#25]
I'm fairly sure I've had no graph updating for the last week.

![image](https://user-images.githubusercontent.com/20361489/151866664-d64bc55e-f262-4935-b7e2-534ca25b3b1c.png)

Here are my settings:
    {
      module: 'MMM-CoinMarketCap',
      position: 'top_center',
      header: 'Cryptocurrencies',
      config: {
        apiKey: 'XXX',
        currencies: [
          'ethereum',
          'bitcoin',
          'solana',
          'litecoin',
          'ftx-token',
          'binance-coin',
          'hedera-hashgraph',
          'luna',
          'xrp',
          'cardano',
          'theta-fuel',
          'polygon',
        ],
        view: 'graphWithChanges',
        graphRange: '1',
        conversion: 'USD',
        showColumnHeaders: false,
        columns: [
          'logo',
          'name',
          'changes',
          'price',
          'graph'
        ],
        significantDigits: 3,
        decimalPlaces: 3
      }

Have tried with graphRange: '1', as well as 7; same graph is showing. Was originally without this line when I tried to troubleshoot.

Thanks for your help and the great plugin!

**Comment by glitch452** [comment]
Took a quick look.  I believe you are correct.  I noticed a change in the URL structure for the graphs from using `USD` to using the CMC internal id... I'll update the module when I have a few minutes.  Thanks for the ticket!

**Comment by glitch452** [comment]
This should be resolved with the latest version, please update.  Thanks!

**Comment by adamlove86** [comment]
Legend! Thank you so much and is working great again!
