### ISSUE TITLE
Stuck on Loading...

### ISSUE THREAD

**Issue by anthony6608** [glitch452/MMM-CoinMarketCap#3]
Hi,

Thank you for this wonderful script. I am in the process of setting up my MM2 and installed your module however I can't get it to work for some reason. I see the "CRYPTOCURRENCIES" header and "Loading.." at the bottom but it doesn't display anything no matter how long I leave it idle.

I used the same code from the docs:

modules: [
        ...
        {
            module: 'MMM-CoinMarketCap',
            position: "top_left",
            header: "Cryptocurrencies",
            config: {
                currencies: ['bitcoin', 'ethereum', 'litecoin', 'ripple'],
                view: 'graphWithChanges',
                conversion: 'CAD',
                ...
                // See below for more Configuration Options
            }
        },

Any idea what may be causing this? 

Thanks in advance!

**Comment by glitch452** [comment]
Hey, so first question, did you also copy in the ellipses (...)?

**Comment by rakgenius** [comment]
Facing the same issue. Magicmirror is stuck on loading

Below is the basic config I have


module: 'MMM-CoinMarketCap',
position: "top_left",
header: "Cryptocurrencies",
config: {
currencies: ['bitcoin', 'ethereum', 'litecoin', 'ripple'],
view: 'graphWithChanges',
conversion: 'EUR,
}

**Comment by glitch452** [comment]
Hello, You seem to be missing a closing quotation after EUR.  Try adding that in and see if it works!

**Comment by rakgenius** [comment]
Sorry that was a copy, paste mistake...Anyway I had to reinstall the magic mirror.
Now confirmed that, if I enable this module then the navigation support using MMM-Carousel won't work. The moment I disable it, everything works fine.

Can you see what's wrong going on in this module?

**Comment by SdeGeata** [comment]
Hello;

   I too am facing the same issue. Does it require **NPM INSTALL**? Here's my config:

`{
    module: 'MMM-CoinMarketCap',
    position: 'bottom_left',
    header: 'Cryptocurrencies',
    	config: {
          currencies: ['bitcoin', 'ethereum', 'litecoin', 'ripple'],
          view: 'graphWithChanges',
          conversion: 'CAD',
                // See below for more Configuration Options
	}
},
`

**Comment by SdeGeata** [comment]
Nevermind, problem solved. Rpi needed a reboot.

Thanks anyway. Gonna go configure the module now. Keep up the good work!
