### ISSUE TITLE
Unable to get data from CoinMarketCap.com

### ISSUE THREAD

**Issue by solid38** [glitch452/MMM-CoinMarketCap#5]
Hi,

For the past few days, I have received the message "Unable to get data from CoinMarketCap.com".
No changes have been made on my side, either on this module or even on another module.
The module is up to date.

Am I the only one in this situation ?

Thanks !

**Comment by glitch452** [comment]
Hi,

It's not just you.  The module uses the old CoinMarketCap Public API which was deprecated and has now been disabled.  I'm in the process of updating to the new CoinMarketCap pro-api, which will unfortunately require an API Key, but at least there is still a free tier that should be sufficient for a typical user of this module. 

To prepare for the new release, you can sign up for the API Key here: https://pro.coinmarketcap.com/signup/

**Comment by solid38** [comment]
Ok thanks ! ^^

**Comment by bigscinto420** [comment]
damn solid38 you beat me by 4 hours lol.  I tried doing it myself but I'm not the most code-savy person lol Thanks for the module though glitch452, Idk why it all of a sudden stopped but it looked amazing until i updated shit on my mirror lol

**Comment by glitch452** [comment]
Fixed!  The latest push to Master has the new API implemented.  Thankfully the API's were similar enough that it didn't require a huge amount of work, and hopefully there are no (new) bugs introduced.  Give it a try any let me know if you have any issues.  Thanks!

**Comment by AvatarED007** [comment]
You have to change the Documentation an move the apiKey to the config part.
In the java-script you check on self.**config**.apiKey

**Comment by glitch452** [comment]
Whoops, yea it's supposed to be in the config part in the README.  I'll update that.  Thanks!

**Comment by solid38** [comment]
It's works !
Thank you very much ;)
