### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by roccotocco** [glitch452/MMM-CoinMarketCap#6]
hello, maybe this can be integrated into the main code.... 
the italian translation.... ple tell how we can switch language. Thanks

{
	"CURRENCY_TITLE": "Valute",
	"PRICE_TITLE": "Prezzo ({conversion_var})",
	"PRICE_USD_TITLE": "Prezzo (USD)",
	"HOUR_TITLE": "Ora",
	"DAY_TITLE": "Giorno",
	"WEEK_TITLE": "Settimana",
	"TREND_TITLE": "Andamento ({range_var})",
	"CHANGES_TITLE": "Cambio",
	"ONE_DAY": "Un giorno",
	"ONE_WEEK": "Una settimana",
	"ONE_MONTH": "Un meseh",
	"UPDATE_SCHEDULED": "Aggiornamento programmato per essere esguito automaticamente ogni {minutes} minuti.",
	"LISTINGS_REQUESTED": "Richiesta valute inviara.",
	"CURRENCY_UPDATE_REQUESTED": "Richiesta di aggiornamento inviata per \"{name}\" utilizzando ID: {id}.",
	"UPDATE_STARTED": "Aggiornamento avviato.",
	"REQUEST_LOGO_DOWNLOAD": "Logo richiesto in download: \"{filename}\".",
	"LISTINGS_SUCCESS": "Dati valuta scaricati con successo dopo {numberOfAttempts} tentativi.",
	"LISTINGS_FAILURE": "Non è stato possibile scaricare i dati! Nuovo tentativo tra {retryTimeInSeconds} secondi.",
	"CURRENCY_UPDATE_SUCCESS": "Aggiornamento della valuta effettuato IDs: {id} dopo {numberOfAttempts} tentativi.",
	"CURRENCY_UPDATE_FAILURE": "Aggiornamento valuta fallita IDs: {id}. Nuovo tentativo tra {retryTimeInSeconds} secondi.",
	"LOGO_DOWNLOAD_SUCCESS": "Logo scaricato con successo: \"{filename}\".",
	"LOGO_DOWNLOAD_FAILURE": "Download del logo fallito: \"{filename}\".",
	"INVALID_CURRENCY": "Impossibile trovate la valuta con id: \"{id}\" o nome: \"{name}\".",
	"LOADING": "Lettura in corso &hellip;",
	"API_ERROR": "Impossibile scaricare i dati da {website}.",
	"SUSPENDED": "Sospeso",
	"RESUMED": "Riattivo",
	"LOGO_SAVE_FAILURE": "Non è stato possibile salvare \"{sourceFilename}\" come: \"{destinationFilename}\".",
	"LOGO_SAVE_SUCCESS": "Salvato con successo \"{sourceFilename}\" come: \"{destinationFilename}\".",
	"API_KEY_REQUIRED": "Per favore specifica la tua chiave API."
}

**Comment by glitch452** [comment]
Hi roccotocco,

Absolutely.  Thanks for working on this!  I've just pushed a commit with the new translation file.  

The module is now able to load the `"it"` language translation file.  All you have to do (if you haven't already) is change the `language` property in the main MagicMirror `config.json` file to `it`.  

Here is an example:
```javascript
var config = {
	...
	language: "it",
	timeFormat: 12,
	units: "metric",
	customCss: "css/custom.css",
	modules: [
		{
			module: "alert",
		},
		...
	]
}
```
