### ISSUE TITLE
Unable to get data from CoinMarketCap

### ISSUE THREAD

**Issue by enjoynering** [glitch452/MMM-CoinMarketCap#7]
Hello,

Firstly, thanks for the module, it seems to be amazing.

I have not been able to set up because of the message:

"Unable to get data from CoinMarketCap"

I have the code like this:
`     {
            module: 'MMM-CoinMarketCap',
            position: "top_left",
            header: "Cryptocurrencies",
            config: {
                apiKey: 'MyApiKey:)',
                currencies: ['bitcoin', 'ethereum', 'litecoin', 'ripple'],
                view: 'graphWithChanges',
                conversion: 'CAD',
                     }
        },

With my own ApiKey :)

Could you help me?

**Comment by thinksnow** [comment]
I'm experiencing the same issue, and when I checked on **api.coinmarketcap.com** in a browser (just to see what happened), I saw this: 

> {"statusCode": 410,"error": "Gone","message": "WARNING: This API is now offline. Please switch to the new CoinMarketCap API. (https://pro.coinmarketcap.com/migrate/)"}

**Comment by glitch452** [comment]
Please make sure you are using v2.0.0 or higher of this module, which uses the new Pro API from CoinMarketCap.  Version v1.x.x of this module uses the old API from CoinMarketCap which is no longer available.

**Comment by thinksnow** [comment]
That did the trick for me, now I need to update my graphics for each coin again. Thank you for the incredibly quick reply.

**Comment by enjoynering** [comment]
Thank you!

Finally I get a new API key and it started working :)
