### ISSUE TITLE
Only EUR conversion works

### ISSUE THREAD

**Issue by solid38** [glitch452/MMM-CoinMarketCap#8]
Hi,

I want to display prices en USD. 
But, only EUR conversion work.
When I tested without conversion option, I had only the dollar symbol without values. If I force USD conversion, it's the same problem.

![2020_04_14_21_06_32_MagicMirror_](https://user-images.githubusercontent.com/54800337/79264053-36ed4380-7e94-11ea-9ccf-bed968bda837.png)

I have tested with CAD conversion and no value is displayed. 

Thank you !

Best regards.

**Comment by solid38** [comment]
Nobody for help me ?

**Comment by glitch452** [comment]
Hi, I'll have to do some testing to see if I can reproduce the problem.  I suspect it could have something to do with the localization settings on your system since this module uses the currency formatting tools built-in to chromium.

**Comment by Rkubinski** [comment]
Same for USD - only displaying the "D" instead of the S - like the "S" in this picture

**Comment by R-Studio** [comment]
Same for CHF - only displaying the "F" instead of the "Fr". Any news?

**Comment by glitch452** [comment]
I think I've found and fixed this.  Please pull the latest version and give it a try.  Let me know if there is still an issue and I'll re-open and take another look.  Thanks!

**Comment by solid38** [comment]
It works.
Thanks for all ;)
